apiVersion: v2
name: command-bot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  # - name: gcloud-sqlproxy
  #   version: "0.22.6"
  #   repository: "https://charts.rimusz.net"
  - name: common
    version: "0.7.2"
    repository: "https://paritytech.github.io/helm-charts/"